In [1]:
import numpy as np

In [3]:
L = np.array([0, -1, 0])
N = np.array([0.894, -0.447, 0])
r = ((2*(N.dot(L)))*(N)) - L
print(r)

[0.799236 0.600382 0.      ]


In [6]:
t = np.array([0.8, 0.6, 0])

print(np.linalg.norm(t))

1.0


In [8]:
print(N.dot(L))

-0.707


In [5]:
data = np.arange(20).reshape(5, 4)
print(data)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [9]:
np.mean(data, axis = 0)

array([ 8.,  9., 10., 11.])